services:
  client:
    container_name: cv-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
    deploy:
      resources:
        limits:
          memory: 2G

  backend:
    container_name: cv-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    deploy:
      resources:
        limits:
          memory: 512M