services:
  cv:
    build: .
    container_name: cv-website
    restart: unless-stopped
    ports:
      - "3001:80"
    volumes:
      # Mount configuration file for easy customization
      - ./config.json:/usr/share/nginx/html/config.json:ro
      # Mount data directory for CV content
      - ./data:/usr/share/nginx/html/assets/external:ro
    
    # networks:
    #   - traefik
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.cv.rule=Host(`cv.nahuelsantos.com`)"
    #   - "traefik.http.routers.cv.entrypoints=websecure"
    #   - "traefik.http.routers.cv.tls.certresolver=letsencrypt"
    #   - "traefik.http.services.cv.loadbalancer.server.port=80"
    #   - "traefik.docker.network=traefik"

# Uncomment for production with Traefik
# networks:
#   traefik:
#     external: trueitoring labels