name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate HTML and Assets
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate HTML
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        root: .
        css: true

    - name: Check required files and assets
      run: |
        echo "Checking for required files and assets..."
        
        # Check core files exist
        required_files=(
          "index.html"
          "style.css" 
          "script.js"
          "data/cv.template.json"
          "data/cv.template.pdf"
          "Dockerfile"
          "nginx.conf"
        )
        
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "❌ Required file missing: $file"
            exit 1
          fi
        done
        
        # Check essential assets exist
        essential_assets=(
          "assets/moon.svg"
          "assets/sun.svg"
          "assets/envelope.svg"
          "assets/download-alt.svg"
          "assets/linkedin.svg"
          "assets/github.svg"
          "assets/location-pin.svg"
          "assets/window-close.svg"
        )
        
        for asset in "${essential_assets[@]}"; do
          if [ ! -f "$asset" ]; then
            echo "❌ Essential asset missing: $asset"
            exit 1
          fi
        done
        
        echo "✅ All required files and assets found"

    - name: Validate JSON template
      run: |
        # Validate template JSON syntax
        python3 -m json.tool data/cv.template.json > /dev/null || {
          echo "❌ cv.template.json is invalid"
          exit 1
        }
        echo "✅ CV template JSON is valid"

    - name: Check CSS syntax
      run: |
        # Basic CSS syntax check - look for common syntax errors
        if grep -E "^\s*[^}]*{[^}]*$" style.css | grep -v "\/\*" | grep -v "\*\/" > /dev/null; then
          # Check for unclosed braces by counting
          open_braces=$(grep -o '{' style.css | wc -l)
          close_braces=$(grep -o '}' style.css | wc -l)
          if [ "$open_braces" -ne "$close_braces" ]; then
            echo "❌ CSS syntax error: Mismatched braces (${open_braces} open, ${close_braces} close)"
            exit 1
          fi
        fi
        # Check for basic CSS structure
        if [ ! -s style.css ]; then
          echo "❌ CSS file is empty"
          exit 1
        fi
        echo "✅ CSS syntax appears valid"

    - name: Check JavaScript syntax
      run: |
        # Basic JS syntax check
        node -c script.js || {
          echo "❌ JavaScript syntax errors found"
          exit 1
        }
        echo "✅ JavaScript syntax is valid"

    - name: Validate manifest.json
      run: |
        # Validate JSON syntax
        python3 -m json.tool manifest.json > /dev/null || {
          echo "❌ manifest.json is invalid"
          exit 1
        }
        echo "✅ manifest.json is valid" 